import 'package:flutter/material.dart';

const Map<String, List<String>> specialtyDiseases = {
  'cardiology': [
    'Hypertension',
    'Coronary Artery Disease',
    'Heart Failure',
    'Arrhythmia',
    'Cardiomyopathy',
  ],
  'dermatology': [
    'Acne',
    'Eczema',
    'Psoriasis',
    'Dermatitis',
    'Skin Infection',
  ],
  'endocrinology': [
    'Type 1 Diabetes',
    'Type 2 Diabetes',
    'Hypothyroidism',
    'Hyperthyroidism',
    'Metabolic Syndrome',
  ],
  'gastroenterology': [
    'Gastritis',
    'GERD',
    'Irritable Bowel Syndrome',
    'Hepatitis',
    'Ulcerative Colitis',
  ],
  'gynecology': [
    'Polycystic Ovary Syndrome',
    'Endometriosis',
    'Uterine Fibroids',
    'Cervicitis',
    'Menstrual Disorder',
  ],
  'hematology': [
    'Iron Deficiency Anemia',
    'Sickle Cell Disease',
    'Thalassemia',
    'Leukopenia',
    'Hemophilia',
  ],
  'nephrology': [
    'Chronic Kidney Disease',
    'Nephritis',
    'Kidney Stones',
    'Proteinuria',
    'Acute Kidney Injury',
  ],
  'neurology': [
    'Migraine',
    'Epilepsy',
    'Stroke',
    'Peripheral Neuropathy',
    'Parkinson Disease',
  ],
  'oncology': [
    'Breast Cancer',
    'Lung Cancer',
    'Colon Cancer',
    'Leukemia',
    'Lymphoma',
  ],
  'ophthalmology': [
    'Cataract',
    'Glaucoma',
    'Conjunctivitis',
    'Diabetic Retinopathy',
    'Dry Eye Syndrome',
  ],
  'orthopedics': [
    'Osteoarthritis',
    'Rheumatoid Arthritis',
    'Fracture',
    'Lumbar Disc Hernia',
    'Tendonitis',
  ],
  'pediatrics': [
    'Bronchiolitis',
    'Otitis',
    'Childhood Asthma',
    'Gastroenteritis',
    'Growth Delay',
  ],
  'psychiatry': [
    'Depression',
    'Generalized Anxiety Disorder',
    'Bipolar Disorder',
    'Schizophrenia',
    'Insomnia',
  ],
  'pulmonology': [
    'Asthma',
    'Chronic Bronchitis',
    'Pneumonia',
    'COPD',
    'Pulmonary Fibrosis',
  ],
  'rheumatology': [
    'Lupus',
    'Gout',
    'Rheumatoid Arthritis',
    'Vasculitis',
    'Ankylosing Spondylitis',
  ],
  'urology': [
    'Urinary Tract Infection',
    'Benign Prostatic Hyperplasia',
    'Kidney Stones',
    'Prostatitis',
    'Urinary Incontinence',
  ],
};

List<String> get specialties => specialtyDiseases.keys.toList()..sort();

List<String> diseasesForSpecialty(String? specialty) {
  if (specialty == null) return const [];
  return specialtyDiseases[specialty.toLowerCase()] ?? const [];
}

List<String> get allDiseases =>
    specialtyDiseases.values.expand((d) => d).toSet().toList()..sort();

const Map<String, Map<String, String>> _specialtyTranslations = {
  'fr': {
    'cardiology': 'Cardiologie',
    'dermatology': 'Dermatologie',
    'endocrinology': 'Endocrinologie',
    'gastroenterology': 'Gastro-entérologie',
    'gynecology': 'Gynécologie',
    'hematology': 'Hématologie',
    'nephrology': 'Néphrologie',
    'neurology': 'Neurologie',
    'oncology': 'Oncologie',
    'ophthalmology': 'Ophtalmologie',
    'orthopedics': 'Orthopédie',
    'pediatrics': 'Pédiatrie',
    'psychiatry': 'Psychiatrie',
    'pulmonology': 'Pneumologie',
    'rheumatology': 'Rhumatologie',
    'urology': 'Urologie',
  },
  'ar': {
    'cardiology': 'أمراض القلب',
    'dermatology': 'الأمراض الجلدية',
    'endocrinology': 'الغدد الصماء',
    'gastroenterology': 'أمراض الجهاز الهضمي',
    'gynecology': 'طب النساء',
    'hematology': 'أمراض الدم',
    'nephrology': 'أمراض الكلى',
    'neurology': 'طب الأعصاب',
    'oncology': 'طب الأورام',
    'ophthalmology': 'طب العيون',
    'orthopedics': 'جراحة العظام',
    'pediatrics': 'طب الأطفال',
    'psychiatry': 'الطب النفسي',
    'pulmonology': 'أمراض الرئة',
    'rheumatology': 'أمراض الروماتيزم',
    'urology': 'طب المسالك البولية',
  },
};

const Map<String, Map<String, String>> _diseaseTranslations = {
  'fr': {
    'Hypertension': 'Hypertension',
    'Coronary Artery Disease': 'Maladie coronarienne',
    'Heart Failure': 'Insuffisance cardiaque',
    'Arrhythmia': 'Arythmie',
    'Cardiomyopathy': 'Cardiomyopathie',
    'Acne': 'Acné',
    'Eczema': 'Eczéma',
    'Psoriasis': 'Psoriasis',
    'Dermatitis': 'Dermatite',
    'Skin Infection': 'Infection cutanée',
    'Type 1 Diabetes': 'Diabète de type 1',
    'Type 2 Diabetes': 'Diabète de type 2',
    'Hypothyroidism': 'Hypothyroïdie',
    'Hyperthyroidism': 'Hyperthyroïdie',
    'Metabolic Syndrome': 'Syndrome métabolique',
    'Gastritis': 'Gastrite',
    'GERD': 'RGO',
    'Irritable Bowel Syndrome': 'Syndrome de l\'intestin irritable',
    'Hepatitis': 'Hépatite',
    'Ulcerative Colitis': 'Rectocolite hémorragique',
    'Polycystic Ovary Syndrome': 'Syndrome des ovaires polykystiques',
    'Endometriosis': 'Endométriose',
    'Uterine Fibroids': 'Fibromes utérins',
    'Cervicitis': 'Cervicite',
    'Menstrual Disorder': 'Trouble menstruel',
    'Iron Deficiency Anemia': 'Anémie ferriprive',
    'Sickle Cell Disease': 'Drépanocytose',
    'Thalassemia': 'Thalassémie',
    'Leukopenia': 'Leucopénie',
    'Hemophilia': 'Hémophilie',
    'Chronic Kidney Disease': 'Maladie rénale chronique',
    'Nephritis': 'Néphrite',
    'Kidney Stones': 'Calculs rénaux',
    'Proteinuria': 'Protéinurie',
    'Acute Kidney Injury': 'Insuffisance rénale aiguë',
    'Migraine': 'Migraine',
    'Epilepsy': 'Épilepsie',
    'Stroke': 'AVC',
    'Peripheral Neuropathy': 'Neuropathie périphérique',
    'Parkinson Disease': 'Maladie de Parkinson',
    'Breast Cancer': 'Cancer du sein',
    'Lung Cancer': 'Cancer du poumon',
    'Colon Cancer': 'Cancer du côlon',
    'Leukemia': 'Leucémie',
    'Lymphoma': 'Lymphome',
    'Cataract': 'Cataracte',
    'Glaucoma': 'Glaucome',
    'Conjunctivitis': 'Conjonctivite',
    'Diabetic Retinopathy': 'Rétinopathie diabétique',
    'Dry Eye Syndrome': 'Syndrome de l\'œil sec',
    'Osteoarthritis': 'Arthrose',
    'Rheumatoid Arthritis': 'Polyarthrite rhumatoïde',
    'Fracture': 'Fracture',
    'Lumbar Disc Hernia': 'Hernie discale lombaire',
    'Tendonitis': 'Tendinite',
    'Bronchiolitis': 'Bronchiolite',
    'Otitis': 'Otite',
    'Childhood Asthma': 'Asthme de l\'enfant',
    'Gastroenteritis': 'Gastro-entérite',
    'Growth Delay': 'Retard de croissance',
    'Depression': 'Dépression',
    'Generalized Anxiety Disorder': 'Trouble anxieux généralisé',
    'Bipolar Disorder': 'Trouble bipolaire',
    'Schizophrenia': 'Schizophrénie',
    'Insomnia': 'Insomnie',
    'Asthma': 'Asthme',
    'Chronic Bronchitis': 'Bronchite chronique',
    'Pneumonia': 'Pneumonie',
    'COPD': 'BPCO',
    'Pulmonary Fibrosis': 'Fibrose pulmonaire',
    'Lupus': 'Lupus',
    'Gout': 'Goutte',
    'Vasculitis': 'Vascularite',
    'Ankylosing Spondylitis': 'Spondylarthrite ankylosante',
    'Urinary Tract Infection': 'Infection urinaire',
    'Benign Prostatic Hyperplasia': 'Hyperplasie bénigne de la prostate',
    'Prostatitis': 'Prostatite',
    'Urinary Incontinence': 'Incontinence urinaire',
  },
  'ar': {
    'Hypertension': 'ارتفاع ضغط الدم',
    'Coronary Artery Disease': 'مرض الشريان التاجي',
    'Heart Failure': 'قصور القلب',
    'Arrhythmia': 'اضطراب نظم القلب',
    'Cardiomyopathy': 'اعتلال عضلة القلب',
    'Acne': 'حب الشباب',
    'Eczema': 'الأكزيما',
    'Psoriasis': 'الصدفية',
    'Dermatitis': 'التهاب الجلد',
    'Skin Infection': 'عدوى جلدية',
    'Type 1 Diabetes': 'داء السكري من النوع الأول',
    'Type 2 Diabetes': 'داء السكري من النوع الثاني',
    'Hypothyroidism': 'قصور الغدة الدرقية',
    'Hyperthyroidism': 'فرط نشاط الغدة الدرقية',
    'Metabolic Syndrome': 'متلازمة الأيض',
    'Gastritis': 'التهاب المعدة',
    'GERD': 'الارتجاع المعدي المريئي',
    'Irritable Bowel Syndrome': 'متلازمة القولون العصبي',
    'Hepatitis': 'التهاب الكبد',
    'Ulcerative Colitis': 'التهاب القولون التقرحي',
    'Polycystic Ovary Syndrome': 'متلازمة تكيس المبايض',
    'Endometriosis': 'بطانة الرحم المهاجرة',
    'Uterine Fibroids': 'الأورام الليفية الرحمية',
    'Cervicitis': 'التهاب عنق الرحم',
    'Menstrual Disorder': 'اضطراب الدورة الشهرية',
    'Iron Deficiency Anemia': 'فقر الدم بنقص الحديد',
    'Sickle Cell Disease': 'فقر الدم المنجلي',
    'Thalassemia': 'الثلاسيميا',
    'Leukopenia': 'نقص الكريات البيضاء',
    'Hemophilia': 'الهيموفيليا',
    'Chronic Kidney Disease': 'مرض الكلى المزمن',
    'Nephritis': 'التهاب الكلى',
    'Kidney Stones': 'حصى الكلى',
    'Proteinuria': 'البيلة البروتينية',
    'Acute Kidney Injury': 'إصابة كلوية حادة',
    'Migraine': 'الصداع النصفي',
    'Epilepsy': 'الصرع',
    'Stroke': 'السكتة الدماغية',
    'Peripheral Neuropathy': 'اعتلال الأعصاب الطرفية',
    'Parkinson Disease': 'مرض باركنسون',
    'Breast Cancer': 'سرطان الثدي',
    'Lung Cancer': 'سرطان الرئة',
    'Colon Cancer': 'سرطان القولون',
    'Leukemia': 'اللوكيميا',
    'Lymphoma': 'اللمفوما',
    'Cataract': 'إعتام عدسة العين',
    'Glaucoma': 'الزرق',
    'Conjunctivitis': 'التهاب الملتحمة',
    'Diabetic Retinopathy': 'اعتلال الشبكية السكري',
    'Dry Eye Syndrome': 'متلازمة جفاف العين',
    'Osteoarthritis': 'الفصال العظمي',
    'Rheumatoid Arthritis': 'التهاب المفاصل الروماتويدي',
    'Fracture': 'كسر',
    'Lumbar Disc Hernia': 'انزلاق غضروفي قطني',
    'Tendonitis': 'التهاب الأوتار',
    'Bronchiolitis': 'التهاب القصيبات',
    'Otitis': 'التهاب الأذن',
    'Childhood Asthma': 'ربو الأطفال',
    'Gastroenteritis': 'التهاب المعدة والأمعاء',
    'Growth Delay': 'تأخر النمو',
    'Depression': 'الاكتئاب',
    'Generalized Anxiety Disorder': 'اضطراب القلق المعمم',
    'Bipolar Disorder': 'الاضطراب ثنائي القطب',
    'Schizophrenia': 'الفصام',
    'Insomnia': 'الأرق',
    'Asthma': 'الربو',
    'Chronic Bronchitis': 'التهاب القصبات المزمن',
    'Pneumonia': 'الالتهاب الرئوي',
    'COPD': 'مرض الانسداد الرئوي المزمن',
    'Pulmonary Fibrosis': 'التليف الرئوي',
    'Lupus': 'الذئبة',
    'Gout': 'النقرس',
    'Vasculitis': 'التهاب الأوعية',
    'Ankylosing Spondylitis': 'التهاب الفقار اللاصق',
    'Urinary Tract Infection': 'التهاب المسالك البولية',
    'Benign Prostatic Hyperplasia': 'تضخم البروستاتا الحميد',
    'Prostatitis': 'التهاب البروستاتا',
    'Urinary Incontinence': 'سلس البول',
  },
};

String _titleCase(String value) {
  if (value.isEmpty) return value;
  return value
      .split(RegExp(r'[\s_-]+'))
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1).toLowerCase())
      .join(' ');
}

String specialtyLabel(String specialty, BuildContext context) {
  final code = Localizations.localeOf(context).languageCode;
  final normalized = specialty.trim().toLowerCase();
  return _specialtyTranslations[code]?[normalized] ?? _titleCase(normalized);
}

String diseaseLabel(String disease, BuildContext context) {
  final code = Localizations.localeOf(context).languageCode;
  final normalized = disease.trim();
  if (normalized.isEmpty) return normalized;
  return _diseaseTranslations[code]?[normalized] ?? normalized;
}
